import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docSidebar: [{ type: 'doc', id: 'index' }],

  javascriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'javascript',
    },
  ],

  reactSidebar: [
    {
      type: 'autogenerated',
      dirName: 'react',
    },
  ],

  typescriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'typescript',
    },
  ],

  cheatSheetSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cheatsheets',
    },
  ],

  interviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'interviews',
    },
  ],
};

export default sidebars;
