name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'automerge'
          MERGE_METHOD: 'squash'
          MERGE_DELETE_BRANCH: 'true'
          MERGE_RETRIES: '6'
          MERGE_RETRY_SLEEP: '60000'
          MERGE_COMMIT_MESSAGE: 'pull-request-title'
